#pragma once

#include <torch/csrc/lazy/core/ir.h>
#include <torch/csrc/lazy/core/ir_builder.h>
#include <torch/csrc/lazy/core/internal_ops/ltc_ops.h>
#include <torch/csrc/lazy/core/shape_inference.h>
#include <torch_xla/csrc/generated_file_include.h>

// This file contains autogenerated LazyTensor Non Native IR nodes

namespace torch_xla {



} // namespace torch_xla
